import pandas as pd

# TODO:
## ADD FIELDS THAT WOULD BE THE SUM, ROUND AND DIVISION FOR THE UPPER
## CATEGORY (LIKE ADAPTABILITY, TRAINABILITY, ETC. FROM 0 TO 5)
## WITH PANDAS: RE-OPEN THE CSV AND ADD THAT COLUMNS AS SUM OF
## OTHER COLUMNS VALUES.

df = pd.read_csv("out.csv", sep=",")
print(df)